name: Docker to ECR

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t myimage:latest .

      - name: Push image to ECR
        run: |
          docker tag myimage:latest \
            ${{ steps.ecr.outputs.registry }}/test-varinder:latest

          docker push \
            ${{ steps.ecr.outputs.registry }}/test-varinder:latest

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --instance-ids "i-0d7f8728e9aaee515" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 010928211341.dkr.ecr.ap-south-1.amazonaws.com",
              "sudo docker pull 010928211341.dkr.ecr.ap-south-1.amazonaws.com/test-varinder:latest",
              "sudo docker stop myapp || true",
              "sudo docker rm myapp || true",
              "sudo docker run -d --name myapp -p 8080:80 010928211341.dkr.ecr.ap-south-1.amazonaws.com/test-varinder:latest"
            ]' \
            --region ap-south-1
