name: Docker to ECR

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t myimage:latest .

      - name: Tag Docker image
        run: |
          docker tag myimage:latest \
          ${{ secrets.ECR_REGISTRY }}/test-varinder:latest

      - name: Push Docker image
        run: |
          docker push \
          ${{ secrets.ECR_REGISTRY }}/test-varinder:latest
